'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createApp}=require('../games/heart/server.cjs');
async function setup(t,opts={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heart-server-'));const app=await createApp({dataDir:dir,...opts});t.after(async()=>{await app.close();assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(dir,{recursive:true,force:true});});return app;}
async function call(app,route,body,cookie='',extra={}){const res=await fetch(app.origin+route,{method:body===undefined?'GET':'POST',headers:{origin:app.origin,'content-type':'application/json','x-bpedia-client':'heartparade',cookie,...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await res.text();let json;try{json=JSON.parse(text);}catch{}return {status:res.status,json,text,cookie:res.headers.get('set-cookie'),headers:res.headers};}
const draw={requestId:'server-draw-001',host:'sanji',comfort:'no-touch',recording:false,consent:true};
test('public player flow, exact retry and pending recovery',async t=>{const app=await setup(t),p=await call(app,'/api/play',draw);assert.equal(p.status,200);assert.equal(p.json.demo,true);assert.equal((await call(app,'/api/state')).json.pending.id,p.json.id);assert.equal((await call(app,'/api/play',draw)).json.id,p.json.id);assert.equal((await call(app,'/api/result',{id:p.json.id})).status,200);});
test('hosting without PIN has no default credentials and cannot issue live tickets',async t=>{const app=await setup(t,{hosted:true});assert.equal((await call(app,'/api/login',{pin:'123456'})).status,503);assert.equal((await call(app,'/api/mode',{mode:'live'})).status,401);assert.equal((await call(app,'/api/admin/state')).status,401);});
test('staff login, mode, real ticket, serve and export',async t=>{const app=await setup(t,{hosted:true,adminPin:'246810'});const login=await call(app,'/api/login',{pin:'246810'});assert.equal(login.status,200);assert.match(login.cookie,/HttpOnly; SameSite=Strict/);const cookie=login.cookie.split(';')[0];assert.equal((await call(app,'/api/admin/settings',{mode:'live'},cookie)).status,200);assert.equal((await call(app,'/api/play',{...draw,verified:true})).status,401);assert.equal((await call(app,'/api/state')).status,401);const r=await call(app,'/api/play',{...draw,verified:true},cookie);assert.equal(r.json.demo,false);assert.equal((await call(app,'/api/admin/ticket',{id:r.json.id,action:'served'},cookie)).json.stats.served,1);assert.match((await call(app,'/api/admin/export',undefined,cookie)).text,/HP-/);});
test('cross-origin mutation, source files and API method abuse are rejected',async t=>{const app=await setup(t);assert.equal((await call(app,'/api/play',draw,'',{origin:'https://evil.example'})).status,403);for(const route of ['/server.cjs','/core/store.cjs','/.local-data/event.json'])assert.equal((await call(app,route)).status,404);assert.equal((await call(app,'/api/play')).status,405);assert.equal((await call(app,'/api/state',[])).status,400);});
test('five invalid PINs lock authentication for sixty seconds',async t=>{let now=100000;const app=await setup(t,{now:()=>now,hosted:true,adminPin:'246810'});for(let i=0;i<5;i++)await call(app,'/api/login',{pin:'000000'});assert.equal((await call(app,'/api/login',{pin:'246810'})).status,429);now+=61000;assert.equal((await call(app,'/api/login',{pin:'246810'})).status,200);});
test('all local HTML asset references load and code has strict CSP',async t=>{const app=await setup(t);for(const route of ['/','/admin.html']){const page=await call(app,route);assert.match(page.headers.get('content-security-policy'),/script-src 'self'/);assert.doesNotMatch(page.text,/<script(?![^>]*src=)[^>]*>/);for(const match of page.text.matchAll(/(?:src|href)="(\/(?:assets|css|js)\/[^"?#]+)"/g)){assert.equal((await call(app,match[1])).status,200,match[1]);}}});
