'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Engine,validateState}=require('../games/heart/core/engine.cjs'),{defaultState,SERVICES}=require('../games/heart/core/catalog.cjs'),{Store}=require('../games/heart/core/store.cjs'),{historyCsv}=require('../games/heart/core/report.cjs');
const options={host:'zoro',comfort:'no-touch',consent:true,recording:false,verified:true};
function engine(extra={}){const store={state:defaultState(),commit(next){this.state=structuredClone(next);}};return new Engine(store,{rng:()=>.4,now:()=>Date.parse('2026-10-03T05:00:00Z'),...extra});}
test('seven requested services and fourteen distinct host combinations',()=>{const e=engine();assert.equal(e.state.services.length,7);assert.deepEqual(e.state.services.map(s=>s.name),["Cinderella's Fit",'Princess Twirl','Blossom Whisper','Sweet Offering',"Knight's Vow",'Warm Hug','Pat on Head']);assert.equal(new Set(e.state.hosts.flatMap(h=>e.state.services.map(s=>h.id+':'+s.id))).size,14);});
test('draw is server selected and retry idempotent before and after acknowledgement',()=>{const e=engine(),r=e.play('request-001',options);assert.equal(r.service.id,'whisper');assert.equal(r.demo,true);assert.deepEqual(e.play('request-001',options),r);assert.throws(()=>e.play('request-002',options),/sebelumnya/);e.acknowledge(r.id);assert.deepEqual(e.play('request-001',options),r);assert.equal(e.state.history.length,1);});
test('consent and comfort validated before any draw',()=>{for(const patch of [{consent:false},{comfort:'unknown'},{recording:undefined},{host:'unknown'}]){const e=engine();assert.throws(()=>e.play('request-consent',{...options,...patch}));assert.equal(e.state.history.length,0);}});
test('each active menu reachable; disabled services and hosts cannot be drawn',()=>{for(let i=0;i<7;i++){const e=engine({rng:()=>i/7});assert.equal(e.play('request-'+i,options).service.id,SERVICES[i].id);}const e=engine();e.updateService('whisper',false);assert.notEqual(e.play('request-disabled',options).service.id,'whisper');e.acknowledge(e.state.pending.id);e.updateHost('zoro',{enabled:false});assert.throws(()=>e.play('request-host',options),/tersedia/);});
test('direct selection obeys allowPick and active services',()=>{const e=engine();assert.equal(e.play('request-pick',{...options,pick:'vow'}).method,'pick');e.acknowledge(e.state.pending.id);e.updateSettings({allowPick:false});assert.throws(()=>e.play('request-pick2',{...options,pick:'vow'}),/belum dibuka/);});
test('pause, closed session and no active services reject new draws',()=>{for(const patch of [{paused:true},{sessionOpen:false}]){const e=engine();e.updateSettings(patch);assert.throws(()=>e.play('request-paused',options),/istirahat/);}const e=engine();e.state.services.forEach(s=>s.enabled=false);assert.throws(()=>e.play('request-empty',options),/menu aktif/);});
test('live requires verified mission, respects queue and daily quota, ack does not serve',()=>{const e=engine();e.updateSettings({mode:'live',queueLimit:1});assert.throws(()=>e.play('request-unverified',{...options,verified:false}),/memeriksa/);const r=e.play('request-live',options);assert.match(r.id,/^HP-/);assert.equal(r.queueNumber,1);e.acknowledge(r.id);assert.equal(e.waiting().length,1);assert.throws(()=>e.play('request-full',options),/Antrean penuh/);e.resolve(r.id,'served');assert.equal(e.waiting().length,0);e.updateHost('zoro',{quota:1});assert.throws(()=>e.play('request-quota',options),/Kuota/);});
test('no-touch substitution preserves the ticket and cannot revive completed tickets',()=>{const e=engine();e.updateSettings({mode:'live'});const r=e.play('request-touch',{...options,comfort:'touch'});e.resolve(r.id,'no-touch');assert.equal(e.state.pending.comfort,'no-touch');e.resolve(r.id,'served');assert.equal(e.state.pending.status,'served');e.resolve(r.id,'served');assert.throws(()=>e.resolve(r.id,'cancelled'),/sudah ditutup/);});
test('cancelled ticket releases quota but never reuses its queue number',()=>{const e=engine();e.updateSettings({mode:'live'});e.updateHost('zoro',{quota:1});const a=e.play('request-cancel',options);e.acknowledge(a.id);e.resolve(a.id,'cancelled');const b=e.play('request-next',options);assert.equal(b.queueNumber,2);});
test('demo practice preserves official records and public view hides history',()=>{const e=engine();e.updateSettings({mode:'live'});const a=e.play('request-real',options);e.acknowledge(a.id);e.updateSettings({mode:'demo'});e.play('request-demo',options);assert.equal(e.state.history.find(r=>r.id===a.id).status,'waiting');assert.equal(e.view().history,undefined);assert.equal(e.view().audit,undefined);assert.equal(e.waiting().length,1);});
test('daily host quota resets at midnight WIB while outstanding queue is preserved',()=>{let time=Date.parse('2026-10-03T16:59:00Z');const e=engine({now:()=>time});e.updateSettings({mode:'live'});e.updateHost('zoro',{quota:1});const a=e.play('request-before',options);e.acknowledge(a.id);time+=120000;assert.equal(e.used('zoro'),0);assert.equal(e.waiting().length,1);assert.equal(e.play('request-after',options).queueNumber,1);});
test('invalid settings, quota and RNG fail without committing',()=>{const e=engine();assert.throws(()=>e.updateSettings({queueLimit:0}));assert.throws(()=>e.updateSettings({anything:true}));assert.throws(()=>e.updateHost('zoro',{quota:1.5}));assert.throws(()=>engine({rng:()=>1}).play('request-rng',options));assert.equal(e.state.revision,0);assert.throws(()=>validateState({...defaultState(),hosts:[]}));});
test('atomic store persists pending ticket and backup, corrupt data never silently resets',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heart-store-'));t.after(()=>{assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(dir,{recursive:true,force:true});});const e=new Engine(new Store(dir));const r=e.play('request-persist',options);assert.equal(new Store(dir).state.pending.id,r.id);assert.ok(fs.existsSync(path.join(dir,'event.json.bak')));fs.writeFileSync(path.join(dir,'event.json'),'{bad');assert.throws(()=>new Store(dir),/tidak direset/);});
test('CSV excludes demos, preserves seven menu names and neutralizes spreadsheet formulas',()=>{const e=engine();e.updateSettings({mode:'live'});e.play('request-report',{...options,username:'=1+1',pick:'cinderella'});const csv=historyCsv(e.state.history);assert.match(csv,/'=1\+1/);assert.match(csv,/Cinderella's Fit/);assert.doesNotMatch(historyCsv(engine().state.history),/DEMO-/);});
