'use strict';
// Declarative workbook content. The authored template supplies styles/charts; every
// derived value retains a formula plus a cache for viewers that do not recalculate.
const {distribution,finalDistribution}=require('../js/game-rules.js');
const tiers={grand:'Hadiah utama',bundling:'Bundling',voucher:'Voucher',product:'Produk',zonk:'Zonk'};
const day=86400000;
function excelDate(value){const d=new Date(value);return Number.isFinite(+d)?Date.UTC(d.getFullYear(),d.getMonth(),d.getDate(),d.getHours(),d.getMinutes(),d.getSeconds())/day+25569:null;}
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function reportModel(state,options={}){
 const now=new Date(options.now??Date.now()),history=state.history.filter(h=>!h.demo),dates=history.map(h=>excelDate(h.at)).filter(Number.isFinite);
 const start=options.start??Math.floor(dates.length?dates.reduce((a,b)=>Math.min(a,b)):excelDate(now)),end=options.end??Math.floor(dates.length?dates.reduce((a,b)=>Math.max(a,b)):excelDate(now)),game=options.game??'Semua';
 const valid=Number.isFinite(start)&&Number.isFinite(end)&&start<=end;
 const gameName=h=>h.game==='boxes'?'Beauty Box':'Spin & Win';
 const selected=history.filter(h=>{const d=excelDate(h.at);return valid&&d>=start&&d<end+1&&(game==='Semua'||gameName(h)===game);});
 const n=selected.length,won=selected.filter(h=>h.prize.tier!=='zonk').length,claimed=selected.filter(h=>h.status==='claimed'&&h.prize.tier!=='zonk').length,zonk=n-won;
 const settings={target:options.target??300,buffer:options.buffer??.2,basis:options.basis??'Peluang saat ini',sample:options.sample??30,claimTarget:options.claimTarget??.95,zonkLimit:options.zonkLimit??.02,gameShare:options.gameShare??.6};
 const sheets={};for(const name of ['Dashboard','Rekomendasi','Rencana Acara','Inventori','Data Permainan','Ringkasan','Panduan'])sheets[name]={cells:{}};
 const put=(s,a,v,f)=>{sheets[s].cells[a]={v:v??null,...(f?{f:f.startsWith('=')?f:'='+f}:{})};};
 const row=(s,r,values)=>values.forEach((v,i)=>put(s,col(i)+r,v));
 const title=(s,text,note)=>{put(s,'A1',text);put(s,'A3',note);};
 const dr=Math.max(6,history.length+5),ir=Math.max(6,state.prizes.length+5),pr=Math.max(14,state.prizes.length+13);
 const data=c=>`'Data Permainan'!$${c}$6:$${c}$${dr}`;
 const criteria=`${data('B')},">="&'Dashboard'!$A$5,${data('B')},"<"&('Dashboard'!$E$5+1),${data('C')},IF('Dashboard'!$I$5="Semua","*",'Dashboard'!$I$5)`;
 const count=extra=>`IF('Ringkasan'!$B$2,COUNTIFS(${criteria}${extra?','+extra:''}),0)`;
 const sum=(c,extra)=>`IF('Ringkasan'!$B$2,SUMIFS(${data(c)},${criteria}${extra?','+extra:''}),0)`;
 const totalStock=state.prizes.reduce((a,p)=>a+p.stock,0),odds=finalDistribution(state),folka=state.campaignId==='pesta-folka-2026';
 title('Dashboard','BPEDIA / EVENT PERFORMANCE','Laporan manajemen · snapshot lokal · hanya hasil mode permainan');
 put('Dashboard','A4','Dari tanggal');put('Dashboard','E4','Sampai tanggal');put('Dashboard','I4','Permainan');
 put('Dashboard','A5',start);put('Dashboard','E5',end);put('Dashboard','I5',game);
 put('Dashboard','A7',valid?'Ubah sel berwarna krem untuk memfilter laporan. Stok kini selalu mengikuti snapshot ekspor.':'Perbaiki filter tanggal: tanggal awal harus sebelum/sama dengan tanggal akhir.',`IF('Ringkasan'!B2,"Ubah sel berwarna krem untuk memfilter laporan. Stok kini selalu mengikuti snapshot ekspor.","Perbaiki filter tanggal: tanggal awal harus sebelum/sama dengan tanggal akhir.")`);
 for(const [a,label,r,v]of [['A','Permainan tersimpan',5,n],['D','Hadiah dikeluarkan',6,won],['G','Tingkat penyerahan',10,won?claimed/won:0],['J','Stok saat ekspor',12,totalStock]]){put('Dashboard',a+'9',label);put('Dashboard',a+'10',v,`'Ringkasan'!B${r}`);}
 put('Dashboard','A14','Belum diserahkan');put('Dashboard','C14',won-claimed,"'Ringkasan'!B8");put('Dashboard','E14','Hasil zonk');put('Dashboard','G14',zonk,"'Ringkasan'!B9");put('Dashboard','I14','Rasio zonk');put('Dashboard','K14',n?zonk/n:0,"'Ringkasan'!B11");
 put('Dashboard','A16','AKTIVITAS MENURUT JAM LOKAL · jumlah permainan dalam periode terpilih');
 put('Dashboard','A31','KOMPOSISI HASIL');put('Dashboard','H31','PERBANDINGAN PERMAINAN');
 put('Dashboard','A44','TINDAKAN SETELAH ACARA');
 put('Dashboard','A45',null,"'Rekomendasi'!C10");put('Dashboard','A47',null,"'Rekomendasi'!C13");
 put('Dashboard','A49','Sumber: riwayat + inventori aplikasi pada waktu ekspor. Frekuensi bermain bukan peserta unik, preferensi terbukti, penjualan atau ROI.');
 title('Data Permainan','DATA PERMAINAN / SUMBER','Satu baris = satu hasil tersimpan. Tidak memuat permainan demo atau data login. Waktu adalah waktu lokal perangkat ekspor.');
 row('Data Permainan',5,['Kode','Waktu lokal','Permainan','ID hadiah','Nama hadiah asli','Kategori','Status saat ekspor','Unit keluar','Unit diserahkan','Jam lokal','Peluang kategori','Durasi (detik)','Nilai diskon','Satuan diskon','Min. belanja (Rp)','Waktu penyerahan','Waktu sumber (ISO)']);
 history.forEach((h,i)=>{const p=h.prize,isVoucher=['voucher','grand'].includes(p.tier);row('Data Permainan',i+6,[h.id,excelDate(h.at),gameName(h),p.id,p.fullName,tiers[p.tier],h.status==='claimed'?'Diserahkan':p.tier==='zonk'?'Zonk':'Belum diserahkan',p.tier==='zonk'?0:1,h.status==='claimed'&&p.tier!=='zonk'?1:0,new Date(h.at).getHours(),Number.isFinite(h.odds?.[p.tier])?h.odds[p.tier]/100:null,Number.isFinite(h.duration)?h.duration/1000:null,isVoucher?p.discount:null,isVoucher?(p.discount<100?'%':'Rp'):null,isVoucher?p.minimum:null,h.claimedAt?excelDate(h.claimedAt):null,h.at]);});
 if(!history.length)row('Data Permainan',6,Array(17).fill(null));sheets['Data Permainan'].body={start:6,end:dr,columns:17,header:5,table:'RiwayatBooth'};
 title('Inventori','INVENTORI / SNAPSHOT','Stok ini adalah sisa saat ekspor, bukan stok awal atau saldo pada tanggal filter. Status foto hanya catatan opsional.');
 row('Inventori',5,['ID hadiah','Nama hadiah asli','Kategori','Stok saat ekspor','Aktif','Catatan foto','Varian / syarat','Diskon','Satuan diskon','Minimum belanja (Rp)','Catatan barang','Foto lokal']);
 state.prizes.forEach((p,i)=>row('Inventori',i+6,[p.id,p.fullName,tiers[p.tier],p.stock,p.enabled?'Ya':'Tidak',['grand','voucher'].includes(p.tier)?'Tidak perlu foto':p.imageChecked?'Sudah ditandai':'Opsional; belum ditandai',p.variant,['grand','voucher'].includes(p.tier)?p.discount:null,['grand','voucher'].includes(p.tier)?(p.discount<100?'%':'Rp'):null,p.minimum??null,p.note,p.image]));
 if(!state.prizes.length)row('Inventori',6,Array(12).fill(null));sheets.Inventori.body={start:6,end:ir,columns:12,header:5,table:'InventoriBooth'};
 title('Ringkasan','RINGKASAN / PERHITUNGAN','Tabel formula yang menjadi sumber grafik dan rekomendasi. Tanggal, game dan status dapat ditelusuri ke Data Permainan.');
 put('Ringkasan','A2','Filter valid');put('Ringkasan','B2',valid,`AND(ISNUMBER('Dashboard'!A5),ISNUMBER('Dashboard'!E5),'Dashboard'!A5<='Dashboard'!E5)`);
 row('Ringkasan',4,['Metrik','Nilai']);
 for(const [r,label,v,f]of [[5,'Permainan',n,count()],[6,'Hadiah keluar',won,sum('H')],[7,'Diserahkan',claimed,sum('I')],[8,'Belum diserahkan',won-claimed,'B6-B7'],[9,'Zonk',zonk,'B5-B6'],[10,'Rasio penyerahan',won?claimed/won:0,'IFERROR(B7/B6,0)'],[11,'Rasio zonk',n?zonk/n:0,'IFERROR(B9/B5,0)'],[12,'Stok saat ekspor',totalStock,`SUM('Inventori'!D6:D${ir})`]]){put('Ringkasan','A'+r,label);put('Ringkasan','B'+r,v,f);}
 const games=['Spin & Win','Beauty Box'],gameCounts=games.map(g=>selected.filter(h=>gameName(h)===g).length);
 put('Ringkasan','H4','Permainan');put('Ringkasan','I4','Jumlah');games.forEach((g,i)=>{put('Ringkasan','H'+(5+i),g);put('Ringkasan','I'+(5+i),gameCounts[i],count(`${data('C')},H${5+i}`));});
 put('Ringkasan','H9','Kategori');put('Ringkasan','I9','Jumlah hasil');Object.entries(tiers).forEach(([k,label],i)=>{put('Ringkasan','H'+(10+i),label);put('Ringkasan','I'+(10+i),selected.filter(h=>h.prize.tier===k).length,count(`${data('F')},H${10+i}`));});
 row('Ringkasan',18,['Jam (angka)']);put('Ringkasan','H18','Jam');put('Ringkasan','I18','Spin & Win');put('Ringkasan','J18','Beauty Box');
 for(let h=0;h<24;h++){const r=19+h;put('Ringkasan','A'+r,h);put('Ringkasan','H'+r,String(h).padStart(2,'0')+':00');games.forEach((g,i)=>put('Ringkasan',(i?'J':'I')+r,selected.filter(x=>gameName(x)===g&&new Date(x.at).getHours()===h).length,count(`${data('J')},A${r},${data('C')},${i?'J':'I'}$18`)));}
 title('Rencana Acara','RENCANA ACARA BERIKUTNYA','Skenario yang bisa diubah. Perhitungan tidak mengubah stok atau peluang aplikasi. Sel krem adalah input manajemen.');
 put('Rencana Acara','A4','Target permainan (asumsi)');put('Rencana Acara','E4','Cadangan stok (asumsi)');put('Rencana Acara','I4','Dasar perhitungan');
 put('Rencana Acara','A5',settings.target);put('Rencana Acara','E5',settings.buffer);put('Rencana Acara','I5',settings.basis);
 put('Rencana Acara','A7','Total rencana unit');put('Rencana Acara','E7','Tambahan dari stok kini');put('Rencana Acara','I7','Biaya hadiah skenario');
 row('Rencana Acara',13,['ID hadiah','Nama hadiah asli','Kategori','Stok kini','Peluang saat ekspor','Keluar sesuai filter','Porsi rencana','Rencana unit','Tambahan unit','Biaya riil/unit (Rp)','Biaya skenario (Rp)','Catatan']);
 let units=0,shortfall=0,missingCost=0,budget=0;const plan=[];
 state.prizes.forEach((p,i)=>{
  const r=i+14,inv=i+6,category=state.prizes.filter(x=>x.enabled&&x.stock>0&&x.tier===p.tier).reduce((a,x)=>a+x.stock,0),chance=p.enabled&&p.stock>0&&category?(odds[p.tier]||0)/100*p.stock/category:0;
  const issued=selected.filter(h=>h.prize.id===p.id&&h.prize.tier!=='zonk').length,share=settings.basis==='Aktual terfilter'?(n>=settings.sample&&p.enabled?issued/n:0):chance;
  const qty=Math.ceil(Number((settings.target*share*(1+settings.buffer)).toPrecision(15))),extra=Math.max(0,qty-p.stock),cost=options.costs?.[p.id];
  units+=qty;shortfall+=extra;if(qty&&cost===undefined)missingCost++;else budget+=qty*(cost||0);
  put('Rencana Acara','A'+r,p.id,`'Inventori'!A${inv}`);put('Rencana Acara','B'+r,p.fullName,`'Inventori'!B${inv}`);put('Rencana Acara','C'+r,tiers[p.tier],`'Inventori'!C${inv}`);put('Rencana Acara','D'+r,p.stock,`'Inventori'!D${inv}`);put('Rencana Acara','E'+r,chance);
  put('Rencana Acara','F'+r,issued,sum('H',`${data('D')},A${r}`));
  put('Rencana Acara','G'+r,share,`IF($I$5="Aktual terfilter",IF(AND('Ringkasan'!$B$5>='Rekomendasi'!$A$5,'Inventori'!E${inv}="Ya"),IFERROR(F${r}/'Ringkasan'!$B$5,0),0),E${r})`);
  put('Rencana Acara','H'+r,qty,`ROUNDUP($A$5*G${r}*(1+$E$5),0)`);put('Rencana Acara','I'+r,extra,`MAX(0,H${r}-D${r})`);put('Rencana Acara','J'+r,cost??null);
  put('Rencana Acara','K'+r,qty===0?0:cost===undefined?'':qty*cost,`IF(H${r}=0,0,IF(ISNUMBER(J${r}),H${r}*J${r},""))`);
  put('Rencana Acara','L'+r,qty===0?'Tidak dialokasikan':cost===undefined?'Isi biaya riil':'Biaya diisi',`IF(H${r}=0,"Tidak dialokasikan",IF(ISNUMBER(J${r}),"Biaya diisi","Isi biaya riil"))`);plan.push({id:p.id,chance,issued,share,qty,extra});
 });
 if(!state.prizes.length)row('Rencana Acara',14,Array(12).fill(null));sheets['Rencana Acara'].body={start:14,end:pr,columns:12,header:13,table:'RencanaBooth'};
 put('Rencana Acara','A8',units,`SUM(H14:H${pr})`);put('Rencana Acara','E8',shortfall,`SUM(I14:I${pr})`);put('Rencana Acara','I8',missingCost?'Biaya belum lengkap':budget,`IF(COUNTIF(L14:L${pr},"Isi biaya riil")>0,"Biaya belum lengkap",SUM(K14:K${pr}))`);
 const planNote=settings.basis==='Aktual terfilter'&&n<settings.sample?'Sampel belum cukup untuk dasar aktual. Pilih Peluang saat ini atau tambah data.':'Perkiraan linear + cadangan, dibulatkan per SKU; tidak mensimulasikan perubahan stok/scarcity. Bukan jaminan hadiah keluar. Biaya hanya hadiah, bukan biaya total acara.';
 put('Rencana Acara','A10',planNote,`IF(AND(I5="Aktual terfilter",'Ringkasan'!B5<'Rekomendasi'!A5),"Sampel belum cukup untuk dasar aktual. Pilih Peluang saat ini atau tambah data.","Perkiraan linear + cadangan, dibulatkan per SKU; tidak mensimulasikan perubahan stok/scarcity. Bukan jaminan hadiah keluar. Biaya hanya hadiah, bukan biaya total acara.")`);
 title('Rekomendasi','REKOMENDASI / DECISION LOG','Aturan yang terlihat dan bisa disetel; keputusan akhir milik manajemen. Isi PIC, tenggat dan status tindak lanjut.');
 row('Rekomendasi',4,['Minimum sampel (asumsi)','Target penyerahan','Ambang review zonk','Ambang porsi game']);row('Rekomendasi',5,[settings.sample,settings.claimTarget,settings.zonkLimit,settings.gameShare]);
 row('Rekomendasi',8,['Area keputusan','Bukti sesuai filter','Rekomendasi tindakan','Prioritas','PIC','Tenggat','Status tindak lanjut']);
 const enough=n>=settings.sample,claimRate=won?claimed/won:0,zRate=n?zonk/n:0;
 const decisions=[
  ['Kualitas sampel',n+' permainan',enough?'Sampel cukup untuk tinjauan awal. Tetap bedakan permainan dari peserta unik dan penjualan.':'Kumpulkan data tambahan sebelum mengubah komposisi game. Rotasikan penawaran kedua game secara setara.',enough?'Tinjau':'Tahan kesimpulan'],
  ['Penyerahan hadiah',(won-claimed)+' belum diserahkan',!won?'Belum ada hadiah pada filter ini. Tidak ada tingkat penyerahan yang dapat dinilai.':claimRate<settings.claimTarget?'Selesaikan pencocokan kode dan penyerahan. Siapkan satu petugas klaim khusus pada acara berikutnya.':won>claimed?'Target rasio tercapai, tetapi masih ada hadiah belum diserahkan. Selesaikan pencocokan kode.':'Penyerahan tercatat lengkap. Pertahankan pencocokan kode sebelum barang diberikan.',won>claimed?'Prioritas':'Terkendali'],
  ['Pilihan permainan',gameCounts[0]+' roda / '+gameCounts[1]+' kotak',!enough?'Belum cukup data untuk menentukan game utama. Uji rotasi posisi dan durasi tayang yang setara.':game!=='Semua'?'Pilih Semua pada filter game sebelum membandingkan kedua permainan.':Math.max(...gameCounts)/n>=settings.gameShare?(gameCounts[0]>gameCounts[1]?'Spin & Win':'Beauty Box')+' mencatat lebih banyak permainan. Uji slot utama dengan rotasi yang setara; ini bukan bukti preferensi atau penjualan.':'Pertahankan dua pilihan permainan; bandingkan dengan durasi tayang dan arahan operator yang setara.','Uji terkontrol'],
  ['Pengalaman zonk',zonk+' zonk',!enough?'Sampel belum cukup untuk menilai rasio zonk. Kumpulkan umpan balik peserta.':zRate>settings.zonkLimit?'Rasio zonk melewati ambang review. Periksa sampel dan umpan balik sebelum menurunkan peluang di admin.':'Rasio zonk berada di bawah ambang review. Pertahankan pengawasan dan transparansi peluang.',enough&&zRate>settings.zonkLimit?'Tinjau':'Pantau'],
  ['Persediaan berikutnya',shortfall+' tambahan unit',shortfall?'Siapkan tambahan stok sesuai sheet Rencana Acara, lalu sesuaikan dengan anggaran, kuota hadiah utama dan kebijakan promo.':'Stok snapshot mencukupi skenario saat ini. Periksa kembali target permainan dan persediaan fisik.','Rencana'],
  ['Biaya dan hasil bisnis',missingCost?missingCost+' biaya unit kosong':'Biaya hadiah terisi',missingCost?'Isi biaya riil per unit pada Rencana Acara. Nominal diskon voucher bukan otomatis biaya yang terealisasi.':'Anggaran hadiah skenario tersedia. Tambahkan biaya booth, staf dan data penjualan secara terpisah sebelum menilai ROI.',missingCost?'Lengkapi data':'Tinjau anggaran']
 ];
 decisions.forEach((d,i)=>row('Rekomendasi',i+9,[...d,null,null,'Belum dimulai']));
 put('Rekomendasi','B9',decisions[0][1],`'Ringkasan'!B5&" permainan"`);put('Rekomendasi','C9',decisions[0][2],`IF('Ringkasan'!B5>=$A$5,"Sampel cukup untuk tinjauan awal. Tetap bedakan permainan dari peserta unik dan penjualan.","Kumpulkan data tambahan sebelum mengubah komposisi game. Rotasikan penawaran kedua game secara setara.")`);put('Rekomendasi','D9',decisions[0][3],`IF('Ringkasan'!B5>=$A$5,"Tinjau","Tahan kesimpulan")`);
 put('Rekomendasi','B10',decisions[1][1],`'Ringkasan'!B8&" belum diserahkan"`);put('Rekomendasi','C10',decisions[1][2],`IF('Ringkasan'!B6=0,"Belum ada hadiah pada filter ini. Tidak ada tingkat penyerahan yang dapat dinilai.",IF('Ringkasan'!B10<$B$5,"Selesaikan pencocokan kode dan penyerahan. Siapkan satu petugas klaim khusus pada acara berikutnya.",IF('Ringkasan'!B8>0,"Target rasio tercapai, tetapi masih ada hadiah belum diserahkan. Selesaikan pencocokan kode.","Penyerahan tercatat lengkap. Pertahankan pencocokan kode sebelum barang diberikan.")))`);put('Rekomendasi','D10',decisions[1][3],`IF('Ringkasan'!B8>0,"Prioritas","Terkendali")`);
 put('Rekomendasi','B11',decisions[2][1],`'Ringkasan'!I5&" roda / "&'Ringkasan'!I6&" kotak"`);put('Rekomendasi','C11',decisions[2][2],`IF('Ringkasan'!B5<$A$5,"Belum cukup data untuk menentukan game utama. Uji rotasi posisi dan durasi tayang yang setara.",IF('Dashboard'!I5<>"Semua","Pilih Semua pada filter game sebelum membandingkan kedua permainan.",IF(MAX('Ringkasan'!I5:I6)/'Ringkasan'!B5>=$D$5,IF('Ringkasan'!I5>'Ringkasan'!I6,"Spin & Win","Beauty Box")&" mencatat lebih banyak permainan. Uji slot utama dengan rotasi yang setara; ini bukan bukti preferensi atau penjualan.","Pertahankan dua pilihan permainan; bandingkan dengan durasi tayang dan arahan operator yang setara.")))`);
 put('Rekomendasi','B12',decisions[3][1],`'Ringkasan'!B9&" zonk"`);put('Rekomendasi','C12',decisions[3][2],`IF('Ringkasan'!B5<$A$5,"Sampel belum cukup untuk menilai rasio zonk. Kumpulkan umpan balik peserta.",IF('Ringkasan'!B11>$C$5,"Rasio zonk melewati ambang review. Periksa sampel dan umpan balik sebelum menurunkan peluang di admin.","Rasio zonk berada di bawah ambang review. Pertahankan pengawasan dan transparansi peluang."))`);put('Rekomendasi','D12',decisions[3][3],`IF(AND('Ringkasan'!B5>=$A$5,'Ringkasan'!B11>$C$5),"Tinjau","Pantau")`);
 put('Rekomendasi','B13',decisions[4][1],`'Rencana Acara'!E8&" tambahan unit"`);put('Rekomendasi','C13',decisions[4][2],`IF('Rencana Acara'!E8>0,"Siapkan tambahan stok sesuai sheet Rencana Acara, lalu sesuaikan dengan anggaran, kuota hadiah utama dan kebijakan promo.","Stok snapshot mencukupi skenario saat ini. Periksa kembali target permainan dan persediaan fisik.")`);
 put('Rekomendasi','B14',decisions[5][1],`IF(COUNTIF('Rencana Acara'!L14:L${pr},"Isi biaya riil")>0,COUNTIF('Rencana Acara'!L14:L${pr},"Isi biaya riil")&" biaya unit kosong","Biaya hadiah terisi")`);put('Rekomendasi','C14',decisions[5][2],`IF(COUNTIF('Rencana Acara'!L14:L${pr},"Isi biaya riil")>0,"Isi biaya riil per unit pada Rencana Acara. Nominal diskon voucher bukan otomatis biaya yang terealisasi.","Anggaran hadiah skenario tersedia. Tambahkan biaya booth, staf dan data penjualan secara terpisah sebelum menilai ROI.")`);put('Rekomendasi','D14',decisions[5][3],`IF(COUNTIF('Rencana Acara'!L14:L${pr},"Isi biaya riil")>0,"Lengkapi data","Tinjau anggaran")`);
 if(folka){
  put('Dashboard','I4','Jalur hasil akhir');put('Dashboard','H31','JALUR HASIL AKHIR');
  put('Dashboard','A49','Satu ronde = satu hasil. Beauty Box adalah bonus yang diperoleh dari roda, bukan pilihan mandiri atau indikator popularitas.');
  put('Data Permainan','A3','Satu baris = satu hasil final. Beauty Box = bonus dari Spin Wheel; awal Mystery belum dihitung. Demo tidak masuk laporan.');
  put('Rencana Acara','A3','Peluang gabungan per ronde: hasil langsung roda + peluang Mystery dikali peluang bonus. Sel krem dapat diubah.');
  put('Rekomendasi','A11','Alur bonus Mystery');
  put('Rekomendasi','C11','Tinjau waktu antrean dan penjelasan operator. Frekuensi bonus mengikuti peluang roda; bukan preferensi terhadap Beauty Box.');
  put('Rekomendasi','D11','Pantau alur');
  put('Rekomendasi','C9',enough?'Sampel cukup untuk tinjauan awal. Bedakan ronde dari peserta unik dan penjualan.':'Tambah sampel sebelum mengubah komposisi hadiah; catat antrean dan umpan balik peserta.',`IF('Ringkasan'!B5>=$A$5,"Sampel cukup untuk tinjauan awal. Bedakan ronde dari peserta unik dan penjualan.","Tambah sampel sebelum mengubah komposisi hadiah; catat antrean dan umpan balik peserta.")`);
 }
 // Mirror formula caches on the presentation sheet, preserving live Excel links.
 sheets.Dashboard.cells.A45.v=sheets.Rekomendasi.cells.C10.v;sheets.Dashboard.cells.A47.v=sheets.Rekomendasi.cells.C13.v;
 title('Panduan','CARA MEMBACA LAPORAN','Snapshot Excel interaktif; perubahan workbook tidak disinkronkan kembali ke aplikasi. Tanpa macro dan tanpa koneksi eksternal.');
 const notes=[['Sumber','Data event lokal Bpedia Spin Studio; hanya riwayat mode permainan. Inventori = sisa saat ekspor.'],['Acara',state.settings.eventName],['Waktu ekspor (lokal)',excelDate(now)],['Waktu ekspor (ISO)',now.toISOString()],['Zona waktu',Intl.DateTimeFormat().resolvedOptions().timeZone],['Revisi event',state.revision],['Versi aplikasi','2.6.0'],['Filter dashboard','Ubah tanggal dan jalur hasil pada Dashboard. Beauty Box adalah bonus dari roda, bukan pilihan game peserta. Grafik/KPI mengikuti filter; stok tetap snapshot.'],['Interaktivitas','Gunakan dropdown game, filter tabel mentah, target permainan/cadangan stok, basis rencana, ambang keputusan, biaya riil, PIC dan status tindak lanjut.'],['Excel','Buka .xlsx di Excel/LibreOffice dan izinkan penghitungan otomatis. Tidak perlu mengaktifkan macro atau konten eksternal.'],['Google Sheets','Bisa diimpor secara manual. Formula dasar dan data disediakan; tampilan grafik/validasi dapat berubah saat konversi. Tidak ada unggahan otomatis ke cloud.'],['Definisi penyerahan','Hadiah dikeluarkan saat hasil dipilih. Status penyerahan adalah status pada waktu ekspor, bukan jumlah klaim yang terjadi pada periode filter.'],['Stock snapshot','Stok berkurang sekali pada hasil final. Mystery belum mengeluarkan hadiah; bonus tanpa zonk. Menutup/mengekspor hasil tidak mengembalikan stok atau menandai penyerahan.'],['Rencana skenario','Target 300 dan buffer 20% adalah asumsi yang bisa diganti. Peluang saat ini menggabungkan roda + bonus. Proyeksi linear; bukan jaminan hasil atau simulasi stok menipis.'],['Dasar aktual','Porsi aktual hanya digunakan bila sampel minimum tercapai. Hadiah dihapus/nonaktif tidak dialokasikan. Hadiah lama yang dihapus tetap berada pada Data Permainan.'],['Biaya','Isi biaya riil hadiah, termasuk biaya voucher hanya bila diketahui. Sel kosong bukan nol. Total biaya tidak ditampilkan sebagai lengkap bila ada biaya unit yang kosong.'],['Batas analisis','Tidak ada data peserta unik, durasi antrean, penjualan, penukaran voucher, margin atau ROI. Tidak ada verifikasi pembelian di aplikasi; jangan menyimpulkannya dari jumlah permainan.'],['Sumber brand','https://beautypediaofc.com/'],['Penerapan keputusan','Tinjau rekomendasi, tetapkan PIC/tenggat/status, lalu terapkan keputusan yang disetujui di dashboard admin pada acara berikutnya. Workbook tidak mengubah permainan otomatis.']];
 row('Panduan',5,['Topik','Keterangan']);notes.forEach((x,i)=>row('Panduan',i+6,x));
 return {version:'2.6.0',sheets,metrics:{n,won,claimed,zonk,totalStock,gameCounts,units,shortfall,missingCost,budget,plan},options:{start,end,game,...settings},exportedAt:now.toISOString()};
}
module.exports={reportModel,excelDate,col};
